# Generated by Django 5.2.6 on 2025-09-20 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('product', models.CharField(default='Tubo PVC 1/2" SDR 315 PSI', max_length=100)),
                ('line', models.CharField(default='Línea #3', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('diameter_mm', models.FloatField(help_text='Diámetro exterior (mm)')),
                ('thickness_mm', models.FloatField(help_text='Espesor (mm)')),
                ('weight_g', models.FloatField(help_text='Peso (g)')),
                ('speed_mpm', models.FloatField(help_text='Velocidad (m/min)')),
                ('defects', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='quality.productionbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='quality_mea_timesta_743ca8_idx'), models.Index(fields=['batch', 'timestamp'], name='quality_mea_batch_i_a4971e_idx')],
            },
        ),
    ]
