# Generated by Django 5.2.6 on 2025-09-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id_defecto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_linea', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('id_defecto_tipo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('lote', models.CharField(max_length=50, null=True)),
                ('turno', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'defecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefectoTipo',
            fields=[
                ('id_defecto_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'defecto_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'linea_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_linea', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('orden', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('t1', models.FloatField(null=True)),
                ('t2', models.FloatField(null=True)),
                ('t3', models.FloatField(null=True)),
                ('t4', models.FloatField(null=True)),
                ('promedio', models.FloatField(null=True)),
                ('th', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroControl',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_linea', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('valor_objetivo', models.FloatField()),
                ('limite_superior', models.FloatField()),
                ('limite_inferior', models.FloatField()),
            ],
            options={
                'db_table': 'parametro_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=50, null=True)),
                ('sdr', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
