# Generated by Django 5.2.6 on 2025-09-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_defecto_defectotipo_lineaproduccion_medicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorProceso',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_producto', models.IntegerField()),
                ('id_linea', models.IntegerField()),
                ('cp', models.FloatField(null=True)),
                ('cpk', models.FloatField(null=True)),
                ('sigma', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'indicador_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id_scrap', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_producido', models.IntegerField(null=True)),
                ('total_defectuoso', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'scrap',
                'managed': False,
            },
        ),
    ]
